//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PBActor.proto
namespace ProtoMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"REQMove")]
  public partial class REQMove : global::ProtoBuf.IExtensible
  {
    public REQMove() {}
    
    private int _posX;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posX
    {
      get { return _posX; }
      set { _posX = value; }
    }
    private int _posY;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"posY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posY
    {
      get { return _posY; }
      set { _posY = value; }
    }
    private int _posZ;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"posZ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posZ
    {
      get { return _posZ; }
      set { _posZ = value; }
    }
    private int _dir;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private int _moveX;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"moveX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int moveX
    {
      get { return _moveX; }
      set { _moveX = value; }
    }
    private int _moveY;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"moveY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int moveY
    {
      get { return _moveY; }
      set { _moveY = value; }
    }
    private long _st;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"st", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long st
    {
      get { return _st; }
      set { _st = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RLTMove")]
  public partial class RLTMove : global::ProtoBuf.IExtensible
  {
    public RLTMove() {}
    
    private int _posX;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posX
    {
      get { return _posX; }
      set { _posX = value; }
    }
    private int _posY;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"posY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posY
    {
      get { return _posY; }
      set { _posY = value; }
    }
    private int _posZ;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"posZ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posZ
    {
      get { return _posZ; }
      set { _posZ = value; }
    }
    private int _dir;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private int _moveX;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"moveX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int moveX
    {
      get { return _moveX; }
      set { _moveX = value; }
    }
    private int _moveY;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"moveY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int moveY
    {
      get { return _moveY; }
      set { _moveY = value; }
    }
    private long _st;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"st", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long st
    {
      get { return _st; }
      set { _st = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BCMove")]
  public partial class BCMove : global::ProtoBuf.IExtensible
  {
    public BCMove() {}
    
    private int _posX;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posX
    {
      get { return _posX; }
      set { _posX = value; }
    }
    private int _posY;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"posY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posY
    {
      get { return _posY; }
      set { _posY = value; }
    }
    private int _posZ;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"posZ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posZ
    {
      get { return _posZ; }
      set { _posZ = value; }
    }
    private int _dir;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private int _moveX;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"moveX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int moveX
    {
      get { return _moveX; }
      set { _moveX = value; }
    }
    private int _moveY;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"moveY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int moveY
    {
      get { return _moveY; }
      set { _moveY = value; }
    }
    private long _st;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"st", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long st
    {
      get { return _st; }
      set { _st = value; }
    }
    private int _uid;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"REQEnterLevel")]
  public partial class REQEnterLevel : global::ProtoBuf.IExtensible
  {
    public REQEnterLevel() {}
    
    private int _sceneId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sceneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sceneId
    {
      get { return _sceneId; }
      set { _sceneId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BCEnterLevel")]
  public partial class BCEnterLevel : global::ProtoBuf.IExtensible
  {
    public BCEnterLevel() {}
    
    private int _sceneId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sceneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sceneId
    {
      get { return _sceneId; }
      set { _sceneId = value; }
    }
    private int _posX;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posX
    {
      get { return _posX; }
      set { _posX = value; }
    }
    private int _posY;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"posY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posY
    {
      get { return _posY; }
      set { _posY = value; }
    }
    private int _posZ;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"posZ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posZ
    {
      get { return _posZ; }
      set { _posZ = value; }
    }
    private int _dir;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private long _st;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"st", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long st
    {
      get { return _st; }
      set { _st = value; }
    }
    private int _uid;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RLTEnterLevel")]
  public partial class RLTEnterLevel : global::ProtoBuf.IExtensible
  {
    public RLTEnterLevel() {}
    
    private int _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private readonly global::System.Collections.Generic.List<RLTEnterLevel.Actor> _actors = new global::System.Collections.Generic.List<RLTEnterLevel.Actor>();
    [global::ProtoBuf.ProtoMember(2, Name=@"actors", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RLTEnterLevel.Actor> actors
    {
      get { return _actors; }
    }
  
    private long _st;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"st", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long st
    {
      get { return _st; }
      set { _st = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Actor")]
  public partial class Actor : global::ProtoBuf.IExtensible
  {
    public Actor() {}
    
    private int _sceneId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sceneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sceneId
    {
      get { return _sceneId; }
      set { _sceneId = value; }
    }
    private int _posX;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posX
    {
      get { return _posX; }
      set { _posX = value; }
    }
    private int _posY;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"posY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posY
    {
      get { return _posY; }
      set { _posY = value; }
    }
    private int _posZ;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"posZ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posZ
    {
      get { return _posZ; }
      set { _posZ = value; }
    }
    private int _moveX;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"moveX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int moveX
    {
      get { return _moveX; }
      set { _moveX = value; }
    }
    private int _moveY;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"moveY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int moveY
    {
      get { return _moveY; }
      set { _moveY = value; }
    }
    private int _dir;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private long _st;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"st", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long st
    {
      get { return _st; }
      set { _st = value; }
    }
    private int _uid;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}