//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Battle.proto
namespace Protocl
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VECTOR3")]
  public partial class VECTOR3 : global::ProtoBuf.IExtensible
  {
    public VECTOR3() {}
    
    private int _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2B_Command")]
  public partial class C2B_Command : global::ProtoBuf.IExtensible
  {
    public C2B_Command() {}
    
    private int _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _skill_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private VECTOR3 _dir = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public VECTOR3 dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"B2C_Command")]
  public partial class B2C_Command : global::ProtoBuf.IExtensible
  {
    public B2C_Command() {}
    
    private int _dt;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dt
    {
      get { return _dt; }
      set { _dt = value; }
    }
    private readonly global::System.Collections.Generic.List<C2B_Command> _commons = new global::System.Collections.Generic.List<C2B_Command>();
    [global::ProtoBuf.ProtoMember(2, Name=@"commons", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<C2B_Command> commons
    {
      get { return _commons; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2B_LoadProgress")]
  public partial class C2B_LoadProgress : global::ProtoBuf.IExtensible
  {
    public C2B_LoadProgress() {}
    
    private int _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _progress;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"progress", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int progress
    {
      get { return _progress; }
      set { _progress = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"B2C_LoadProgress")]
  public partial class B2C_LoadProgress : global::ProtoBuf.IExtensible
  {
    public B2C_LoadProgress() {}
    
    private readonly global::System.Collections.Generic.List<C2B_LoadProgress> _progresses = new global::System.Collections.Generic.List<C2B_LoadProgress>();
    [global::ProtoBuf.ProtoMember(1, Name=@"progresses", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<C2B_LoadProgress> progresses
    {
      get { return _progresses; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ECommon")]
    public enum ECommon
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartMove", Value=1)]
      StartMove = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StopMove", Value=2)]
      StopMove = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FireSkill", Value=3)]
      FireSkill = 3
    }
  
}