//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: User.proto
// Note: requires additional types generated from: Player.proto
namespace Protocl
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2L_Login")]
  public partial class C2L_Login : global::ProtoBuf.IExtensible
  {
    public C2L_Login() {}
    
    private int _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"L2C_Login")]
  public partial class L2C_Login : global::ProtoBuf.IExtensible
  {
    public L2C_Login() {}
    
    private PlayerBase _player_base;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_base", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PlayerBase player_base
    {
      get { return _player_base; }
      set { _player_base = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}